### ISSUE TITLE
Rewrite "str" to "tkr"

### ISSUE THREAD

**Issue by Netlob** [nlscript/nlscript#1]
Een string is nu nog str maar zou "tekenreeds" oftewel "tkr" moeten worden :')

ps sicke taal

**Comment by keesvv** [comment]
Haha dank je wel, @Netlob! :smile:

Ik ben dit project puur voor de lol gestart overigens, dus creëer niet te veel verwachtingen.

"str" in het voorbeeld was toevallig de naam van de variabele. Tot nu toe ben ik van plan dit een dynamic/niet strong-typed taal te maken, maar dit kan natuurlijk altijd nog veranderen in de toekomst.

Ik zal het straks in het voorbeeld aanpassen, dat ziet er leuker uit :wink:.

**Comment by keesvv** [comment]
Ik heb het voorbeeld aangepast en ik sluit deze issue. Thx voor de input!
